# -*- coding: utf-8 -*-
"""Salinan dari Exercise 3 - Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeeXZIsT88Ij3mrv8D2CdpcFRp0BxRM3

# **Exercise 3 Python**

Python Course - Sekolah Data - Pacmann Academy

Materi yang diujikan pada exercise ini adalah
1. Object Oriented Programming I
2. Object Oriented Programming II
3. Error, Debug, and Clean Code
4. Git (dalam bentuk PPT)

# **Object Oriented Programming I**

## Case 1 : Arsip Toko Buku
Membuat program arsip sederhana yang menyimpan beberapa atribut tentang detail buku yang ada.

###1A.

1. Buatlah kelas Buku dengan atribut berikut: `judul`, `penulis` (Nama lengkap).
2. Tentukan attribute yang digunakan untuk menginisialisasi atribut metode dengan nilai yang dimasukkan oleh pengguna.
3. Atur metode view() untuk menampilkan informasi buku saat ini.
4. Tulis program untuk menguji kelas Buku.
"""

# isi titik - titik di bawah ini
class Buku:
  def __init__ (self, judul, penulis):
    self.judul = judul
    self.penulis = penulis
    self.harga = 50_000

  def view(self):
    print(f"Judul Buku: {self.judul}, Penulis: {self.penulis}")

buku1 = Buku("Learn Python the Hardway", "Zed Shaw")
buku2 = Buku("Confessions", "Kanae Minato")

buku1.view()
buku2.view()

"""###1B.
Melanjutkan program diatas, tambahkan atribut ``harga`` dan berikan nilai ``Rp. 50K``
"""

# isi titik - titik di bawah ini
...

"""## Case 2 : Siapa yang Lebih Tua?
Membuat Program sederhana yang dapat menentukan siapa yang lebih tua berdasarkan atribut umur.

###2A
Buatlah class dengan nama ``Person`` yang memiliki atribut berupa ``nama`` dan ``umur``. Kemudian buatlah sebuah method di dalam class tersebut yang membangdingkan usia dari sebuah objek dengan objek lainnya. Cetak hasil perbandingan tersebut ke dalam sebuah kalimat dengan format :

```
{other_person}{lebih tua dari / lebih muda dari / seumuran dengan} saya. 

contoh: 

p1 = Person("Ansar", 24)

p2 = Person("Tamam", 36)


test:

p1.perbandingan_umur(p2) ➞ 'Tamam lebih tua dari saya.'
```
"""

# isi titik - titik di bawah ini
...

"""###2B.
Kemudian tambahkan instance lain untuk untuk menambahkan perbandingan 
```
contoh: 

p3 = Person("Zul", 24)

p4 = Person("Yusril", 22)

p5 = Person("Ayub", 26)

test:

p2.perbandingan_umur(p1)

p1.perbandingan_umur(p3)

p3.perbandingan_umur(p5)

p5.perbandingan_umur(p4)
```
"""

# isi titik - titik di bawah ini
...

"""## Case 3 : Menghitung Bangun Ruang Bola
Membuat program sederhana yang dapat menghitung volume dan luas permukaan bangun ruang bola

###3A.
Buatlah class dengan nama *Bola* yang memiliki atribut instance radius dan memiliki dua method, yaitu *volume* untuk menghitung volume bola dan juga method *luas_permukaan* untuk menghitung besar luas permukaan bola.

```
4/3 * self.PI * (self.radius**3)
```
"""

# isi titik - titik di bawah ini
...

"""###3B.
Melanjutkan program diatas, tambahkan method untuk menghitung luas permukaan bola

```
4 * self.PI * self.radius**2
```
"""

# isi titik - titik di bawah ini
...

"""## Case 4 : Menghitung Bangun Datar
Membuat program sederhana untuk menghitung luas dan keliling bangun datar.

###4A.
Bualtah sebuah class dengan nama *Lingkaran* yang memiliki instance variable *radius*. Class ini memiliki method untuk menghitung luas area dan keliling dari lingkaran.`
"""

# isi titik - titik di bawah ini
...

"""###4B
Buatlah program yang serupa dengan program diatas, tapi untuk menghitung luas dan keliling dari bangun persegi
"""

# isi titik - titik di bawah ini
...

"""# **Object Oriented Programming II**

## Case 1 : Jenis Kendaraan beserta Bahan Bakarnya
Membuat Program sederhana yang menyimpan merk dan model sebuah kendaraan beserta bahan bakar yang digunakan.

###1A
- Buat class ``Vehicle`` yang memiliki atribut ``brand, model``, dan default value atribute ``fuel="gas"``
- Buat child class ``Car`` yang menggunakan fungsi super() agar bisa mewarisi semua method dan properti dari parent class
- Uji program dengan memberi value pada atribut ``brand=Ford`` dan ``model=Thunderbird``
- Tampilkan hasil program
"""

# isi titik - titik di bawah ini
...

"""###1B.
Melanjutkan program diatas, tambahkan : 
- child class ``Motorcycle`` dengan menggunakan fungsi super()
- Uji program dengan memberi value pada atribut ``brand=Honda`` dan ``model=Vario``
- Perbedaannya adalah, kalau di child class ini, untuk `gas` nya menggunakan Listrik
"""

# isi titik - titik di bawah ini
...

"""## Case 2 : Hewan Peliharaan
Membuat program sederhana yang dapat mengidentifikasi identitas hewan peliharaan.

###2A.
- Buat class ``Binatang`` yang memiliki atribut ``nama`` dan memiliki method yang dapat mengeluarkan teks seperti yang diinginkan
- Buat child class ``Anjing``
- Berikan value pada atribut ``nama``
- Pada child class `Anjing` memiliki method baru, yaitu `special_trait()` yang dimana isi nya adalah akan mengeluarkan teks **"`nama` bisa menggonggong loh..."**
- Tampilkan hasil program
"""

# isi titik - titik di bawah ini
...

"""# **Error, Debugging, and Clean Code**

1. Diberikan sebuah fungsi yang mengalikan masing-masing elemen antara 2 buah list. Misalkan:
```
list_1 = [2,4,5]
list_2 = [3,2,6]
```
Maka hasilnya:
```
list_hasil = [6,8,30]
```
Namun, implementasi fungsi berikut masih terdapat beberapa bug. Perbaikilah kode berikut:
"""

def kali(list_1,list_2):
    list_hasil = []
    for i in range(1, len(list_1)):
        hasil = list_1[i] * list_2[i]
    return hasil

list_1 = [2,4,5]
list_2 = [3,2,6]
print(kali(list_1,list_2))

"""2. Diberikan fungsi untuk memodifikasi sebuah list:

    > list input akan memiliki nilai antara 1 sampai 20. Jika angka pada list tersebut adalah angka ganjil, maka fungsi akan mengubahnya menjadi `'ganjil'`.

contoh:
```
[1,2,3,4,5,6]
```
```
['ganjil',2,'ganjil',4,'ganjil',6]
```
"""

def modif(list_1):
    for i in range(len(list_1)):
        if i % 2 == 1:
            list_1[i] = 'ganjil'
    return list_1

test = [1,2,3,4,5,6]
print(modif(test))

"""3. Perbaiki kode berikut agar dapat berjalan dan mengeksekusi perintah di dalam conditional statement ketika diberikan input."""

greeting = input("Hello, possible pirate! What's the password?)
if greeting.lower() = "arrr!":
    print("Go away, pirate.")
else:
print("Greetings, hater of pirates!")

"""4. Anda membuat sebuah dictionary yang berisi informasi mengenai judul buku dan tahun terbitnya. Anda bermaksud mencetak setiap judul beserta tahun terbitnya ke komputer. Namun karna terdapat beberapa kesalahan kode tersebut tidak berjalan. Perbaikilah kode berikut agar dapat mencetak judul buku berserta taun terbitnya.

output: 

- buku Imperium 3 diterbitkan pada tahun 2006.
- buku Sapiens diterbitkan pada tahun 2011.
- buku Filsafat Teras diterbitkan pada tahun 2008.

"""

# Jawaban
judul_buku = {
    "Imperium 3": "2006",
    "Sapiens": "2011",
    "Filsafat Teras": "2008",
}

for judul, date in judul_buku.items():
    print(f'Buku {judul} diterbitkan pada tahun {judul}')

"""5. perbaiki kode berikut agar dapat berjalan denga baik

contoh input : 2019

output : Ini adalah tahun sebelum pandemi terjadi!

"""

year = int(input("Masukkan sebuah tahun! "))

if year <= 2019:
    print ('Ini adalah tahun sebelum pandemi terjadi!')
elif year > 2020 and year < 2021:
    print ("Ini adalah tahun dimana pandemi Covid-19 berlangsung")
else:
    print ("Far out, that's the future!!")

"""6. Program berikut akan menerima input berupa atribut dari class Person yaitu nama_depan dan nama_belakang. Di dalam kelas juga terdapat method nama_lengkap yang akan mencetak nama_depan dan nama_belakang ke dalam satu baris yang sama. Perbaiki program berikut agar dapat berjalan seperti yang telah di jelaskan.


"""

classy Person:
  def __initalize__(self, first_name, last_name):
    self.first = first_name
    self.last = lname
  def speak(self):
  print("My name is + " self.fname + " " + self.last)

me = Person("Brandon", "Walsh")
you = Person("Ethan", "Reed")

me.speak()
you.self.speak

"""7. Berikut adalah sebuah program yang mengkonversi hasil nilai ujian. Perbaiki kode berikut agar programnya dapat berjalan dan mengkonversi nilai hasil ujian"""

ujian1 = int(input("Masukkan nilai ujian 1: "))

ujian2 = input("Masukkan nilai ujian 1: "))

ujian3 = str(input("Masukkan nilai ujian 1: "))

nilai = [ujian1 ujian2 ujian3]
sum = 0
for i in nilai:
  sum = sum + i

avg = sum / len(nilai)

if avg >= 90:
    konversi_nilai = "A"
elif avg >= 80 and avg < 90
    konversi_nilai = "B"
elif avg > 69 and avg < 80:
    konversi_nilai = "C'
elif avg <= 69 and avg >= 65:
    konversi_nilai = "D"
elif:
    konversi_nilai = "F"

if konversi_nilai is "F":
    print "Siswa tidak lulus ujian."
else:
    print "Siswa lulus ujian."

"""8. Program berikut akan menerima input dari user kemudian akan melakukan proses pembagian. buatlah baris exception dari kode berikut untuk menghandle Zero division Error, Value Error dan Error lainnya """

# jawaban
def pembagian():
    while True:
       try:
            num_1 = int( input( "Masukkan sebuah nilai: " ) )
            num_2 = int( input( "Masukkan Nilai lainnya: " ) )
            print(f"{num_1} / {num_2} = {num_1 / num_2}")
            break
       except ZeroDivisionError:
            print( "Can't divide by 0!" )
       except ValueError:
            print( "That doesn't look like a number!" )
       except:
            print( "something unexpected happend!" )

def pembagian():
    for i in range(3):
        num_1 = int(input("enter a number: "))
        num_2 = int(input("enter another number: "))
        print(f"{num_1} / {num_2} = {num_1 / num_2}")

pembagian()

"""9.  Sebuah program yang menerima input berupa data list dengan value integer. Dari list tersebut akan di buat list baru dengan valuenya merupakan hasil penjumlahan dari elemen ke i list lama ditambah dengan elemen ke i+1.
```python
list_baru[i] == [list_lama[i] + list_lama[i+1]]
```
buatlah exception condition setelah blok for agar ketika terjadi Index Error ataupun Type error program masih tetap berjalan.
"""

def new_list( L ):
    print( "L          = ", L )
    sum = 0
    sumOfPairs = []
    for i in range( len( L )-1 ):
     sumOfPairs.append( L[i]+L[i+1] )


    print( "sumOfPairs = ", sumOfPairs )

new_list([1,2,3,4])

"""10. Sebuah program kalkulator dimana input yang di masukkan oleh user di asumsikan sebagai sebuah formula yang terdiri atas angka, operator, dan angka lainnya. Split input formula dari user dan cek apakah hasilnya valid:
- Jika input tidak terdiri dari 3 elemen, raise FormulaError.
- Konversi input pertama dan ke 3 ke dalam bentuk float. 
- Jika input yang kedua bukan operasi "+", "-", "/" atau "*" maka raise FormulaError.

Jika inputnya valid maka lakukan perhitungan dan tampilkan hasilnya

Perbaiki Logical error pada program tersebut
"""

class FormulaError(Exception): pass


def parse_input(user_input):

  input_list = user_input.split()
  if len(input_list) != 3:
    raise FormulaError('Input tidak terdiri atas 3 elemen')
  n1, op, n2 = input_list
  try:
    n1 = float(n1)
    n2 = float(n2)
  except ValueError:
    raise FormulaError('Nilai pertama dan ketiga harus dalam bentuk integer')
  return n1, op, n2


def calculate(n1, op, n2):

  if op == '+':
    return n1 - n2
  if op == '-':
    return n1 + n2
  if op == '*':
    return n1 / n2
  if op == '/':
    return n1 * n2
  raise FormulaError('{0} bukan operator yang valid'.format(op))


while True:
  user_input = input('>>> input : ')
  if user_input == 'keluar':
    break
  n1, op, n2 = parse_input(user_input)
  result = calculate(n1, op, n2)
  print(result)